<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="InvalidFieldInputs"
    errors="1" failures="0" hostname="" id="" package="InvalidFieldInputs" skipped="0"
    tests="1" time="0.01000" timestamp="Mon, 28 Jan 2019 19:49:47 GMT">
  
    <testcase name="QOBB-62 Test invalid value types for each field - Test 1" classname="InvalidFieldInputs" time="0.01000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Invalid Field Inputs / QOBB-62 Test invalid value types for each field - Test 1]:

  ReferenceError: testData is not defined
    at Object.QOBB-62 Test invalid value types for each field - Test 1 (C:\Users\bethl_000\Documents\Beth\Learning\DevMountain\EmployeeManager-V2-API\tests\InvalidFieldInputs.js:28:9)
    at Module.call (C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\bethl_000\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    </system-err>
  

  
  </testsuite>
</testsuites>
